package com.got.retailpos.payments;

import static org.assertj.core.api.Assertions.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal; import java.time.Instant; import java.util.*; import java.util.concurrent.ConcurrentHashMap; import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.test.context.TestConfiguration; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.context.annotation.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import com.got.retailpos.*; import com.got.retailpos.catalog.application.ProductCatalogService; import com.got.retailpos.catalog.domain.Product; import com.got.retailpos.identity.application.UserAccountService; import com.got.retailpos.identity.domain.Role; import com.got.retailpos.identity.security.RetailUserPrincipal; import com.got.retailpos.inventory.application.*; import com.got.retailpos.inventory.infrastructure.*; import com.got.retailpos.payments.application.*; import com.got.retailpos.payments.domain.*; import com.got.retailpos.payments.infrastructure.*; import com.got.retailpos.sales.application.*; import com.got.retailpos.sales.domain.*;
import jakarta.persistence.EntityManager;

@Import({TestcontainersConfiguration.class,PromptPayIntegrationTests.GatewayConfig.class})
@SpringBootTest(properties={"app.reservation-expiry-interval-ms=3600000","app.stripe.webhook-secret=whsec_testsecret"}) @AutoConfigureMockMvc @Transactional
class PromptPayIntegrationTests {
	@Autowired ProductCatalogService catalog; @Autowired UserAccountService users; @Autowired SupplierService suppliers; @Autowired InventoryService inventory; @Autowired SalesService sales; @Autowired PromptPayService promptPay; @Autowired PromptPayTransactions transactions; @Autowired ReservationExpiryJob expiryJob; @Autowired InventoryBalanceRepository balances; @Autowired StockMovementRepository movements; @Autowired PaymentRepository payments; @Autowired StockReservationRepository reservations; @Autowired FakeGateway gateway; @Autowired JdbcTemplate jdbc; @Autowired EntityManager entityManager; @Autowired MockMvc mockMvc;
	Product product; RetailUserPrincipal cashier;
	@BeforeEach void setup(){gateway.reset();var category=catalog.createCategory("pay-"+UUID.randomUUID());product=catalog.createProduct(new ProductCatalogService.ProductInput(category.getId(),"PAY-"+UUID.randomUUID(),null,"สินค้า PromptPay",new BigDecimal("100.00"),0));cashier=principal("cashier",Role.CASHIER);var manager=principal("manager",Role.MANAGER);var supplier=suppliers.create(new SupplierService.SupplierInput("supplier-"+UUID.randomUUID(),null,null));inventory.postReceipt(new InventoryService.ReceiptInput(supplier.getId(),"GR-"+UUID.randomUUID(),Instant.now().minusSeconds(1),null,List.of(new InventoryService.ReceiptItemInput(product.getId(),3,new BigDecimal("60.0000")))),manager.id());}

	@Test void shouldReserveForTenMinutesAndReuseSameIdempotencyKey(){var sale=sale(2);var pending=promptPay.initiate(sale.getId(),"prompt-key",cashier.id());var again=promptPay.initiate(sale.getId(),"prompt-key",cashier.id());assertThat(again.paymentIntentId()).isEqualTo(pending.paymentIntentId());assertThat(gateway.creates).hasValue(1);var balance=balances.findById(product.getId()).orElseThrow();assertThat(balance.getOnHand()).isEqualTo(3);assertThat(balance.getReserved()).isEqualTo(2);assertThat(balance.getAvailable()).isEqualTo(1);assertThat(pending.expiresAt()).isBetween(Instant.now().plusSeconds(590),Instant.now().plusSeconds(610));assertThatThrownBy(()->promptPay.initiate(sale(2).getId(),"second-sale",cashier.id())).isInstanceOf(IllegalArgumentException.class);}

	@Test void shouldCompleteOnlyOnceWhenWebhookIsDuplicated(){var sale=sale(1);var pending=promptPay.initiate(sale.getId(),"success-key",cashier.id());gateway.status=PromptPayGateway.ProviderStatus.SUCCEEDED;promptPay.processWebhook("evt-success","payment_intent.succeeded",pending.paymentIntentId());promptPay.processWebhook("evt-success","payment_intent.succeeded",pending.paymentIntentId());var completed=sales.findById(sale.getId());assertThat(completed.getStatus()).isEqualTo(SaleStatus.COMPLETED);assertThat(completed.getReceiptNumber()).startsWith("R-");var balance=balances.findById(product.getId()).orElseThrow();assertThat(balance.getOnHand()).isEqualTo(2);assertThat(balance.getReserved()).isZero();assertThat(movements.findAllByProductId(product.getId(),org.springframework.data.domain.Pageable.unpaged()).stream().filter(m->m.getMovementType()==com.got.retailpos.inventory.domain.MovementType.SALE)).hasSize(1);assertThat(jdbc.queryForObject("select count(*) from stripe_events where event_id='evt-success'",Integer.class)).isEqualTo(1);}

	@Test void shouldUseCurrentProviderStateWhenEventsArriveOutOfOrder(){var sale=sale(1);var pending=promptPay.initiate(sale.getId(),"out-of-order",cashier.id());gateway.status=PromptPayGateway.ProviderStatus.SUCCEEDED;promptPay.processWebhook("evt-failed-first","payment_intent.payment_failed",pending.paymentIntentId());promptPay.processWebhook("evt-succeeded-later","payment_intent.succeeded",pending.paymentIntentId());assertThat(sales.findById(sale.getId()).getStatus()).isEqualTo(SaleStatus.COMPLETED);assertThat(balances.findById(product.getId()).orElseThrow().getOnHand()).isEqualTo(2);}

	@Test @Transactional(propagation=org.springframework.transaction.annotation.Propagation.NOT_SUPPORTED)
	void shouldRollbackUnknownPaymentIntentSoStripeCanRetry(){gateway.status=PromptPayGateway.ProviderStatus.SUCCEEDED;assertThatThrownBy(()->promptPay.processWebhook("evt-too-early","payment_intent.succeeded","pi_not_attached_yet")).isInstanceOf(IllegalStateException.class);assertThat(jdbc.queryForObject("select count(*) from stripe_events where event_id='evt-too-early'",Integer.class)).isZero();}

	@Test void shouldReleaseReservationWhenPaymentFails(){var sale=sale(2);var pending=promptPay.initiate(sale.getId(),"failed-key",cashier.id());gateway.status=PromptPayGateway.ProviderStatus.FAILED;promptPay.processWebhook("evt-failed","payment_intent.payment_failed",pending.paymentIntentId());assertThat(sales.findById(sale.getId()).getStatus()).isEqualTo(SaleStatus.EXPIRED);assertThat(payments.findBySaleId(sale.getId()).orElseThrow().getStatus()).isEqualTo(PaymentStatus.FAILED);assertThat(reservations.findBySaleId(sale.getId()).orElseThrow().getStatus()).isEqualTo(ReservationStatus.RELEASED);assertThat(balances.findById(product.getId()).orElseThrow().getReserved()).isZero();}

	@Test void shouldExpireReservationAndCancelPaymentIntent(){var sale=sale(1);var pending=promptPay.initiate(sale.getId(),"expiry-key",cashier.id());entityManager.flush();jdbc.update("update stock_reservations set expires_at=? where sale_id=?",java.sql.Timestamp.from(Instant.now().minusSeconds(1)),sale.getId());entityManager.clear();expiryJob.expire();assertThat(sales.findById(sale.getId()).getStatus()).isEqualTo(SaleStatus.EXPIRED);assertThat(payments.findBySaleId(sale.getId()).orElseThrow().getStatus()).isEqualTo(PaymentStatus.CANCELLED);assertThat(balances.findById(product.getId()).orElseThrow().getReserved()).isZero();assertThat(gateway.cancelled).containsExactly(pending.paymentIntentId());}

	@Test void shouldRejectUnsignedWebhookWithoutSessionOrCsrf() throws Exception {mockMvc.perform(post("/api/v1/payments/stripe/webhook").header("Stripe-Signature","invalid").content("{\"id\":\"evt_bad\"}" )).andExpect(status().isBadRequest());}
	@Test void shouldVerifySignedWebhookAndCompleteWithoutSessionOrCsrf() throws Exception {var sale=sale(1);var pending=promptPay.initiate(sale.getId(),"signed-webhook",cashier.id());gateway.status=PromptPayGateway.ProviderStatus.SUCCEEDED;var payload="""
{"id":"evt_signed","object":"event","type":"payment_intent.succeeded","data":{"object":{"id":"%s","object":"payment_intent"}}}
""".formatted(pending.paymentIntentId()).strip();var timestamp=Instant.now().getEpochSecond();var signature=stripeSignature(timestamp,payload,"whsec_testsecret");mockMvc.perform(post("/api/v1/payments/stripe/webhook").header("Stripe-Signature",signature).contentType("application/json").content(payload)).andExpect(status().isNoContent());assertThat(sales.findById(sale.getId()).getStatus()).isEqualTo(SaleStatus.COMPLETED);}

	private Sale sale(int quantity){return sales.create(new SalesService.CreateSaleInput(null,List.of(new SalesService.SaleItemInput(product.getId(),quantity))),cashier.id());}
	private RetailUserPrincipal principal(String prefix,Role role){var username=prefix+"-"+UUID.randomUUID();return RetailUserPrincipal.from(users.create(username,"correct-password",username,role));}
	private String stripeSignature(long timestamp,String payload,String secret) throws Exception {var mac=javax.crypto.Mac.getInstance("HmacSHA256");mac.init(new javax.crypto.spec.SecretKeySpec(secret.getBytes(java.nio.charset.StandardCharsets.UTF_8),"HmacSHA256"));var digest=mac.doFinal((timestamp+"."+payload).getBytes(java.nio.charset.StandardCharsets.UTF_8));return "t="+timestamp+",v1="+HexFormat.of().formatHex(digest);}

	@TestConfiguration static class GatewayConfig {@Bean @Primary FakeGateway promptPayGateway(){return new FakeGateway();}}
	static class FakeGateway implements PromptPayGateway {
		final AtomicInteger creates=new AtomicInteger(); final List<String> cancelled=new ArrayList<>(); final Map<String,String> keys=new ConcurrentHashMap<>(); ProviderStatus status=ProviderStatus.PENDING;
		@Override public CreatedPayment create(BigDecimal amount,UUID saleId,UUID paymentId,String key){creates.incrementAndGet();var id=keys.computeIfAbsent(key,ignored->"pi_"+UUID.randomUUID());return new CreatedPayment(id,"https://example.test/qr.png",status);}
		@Override public ProviderStatus retrieveStatus(String id){return status;}
		@Override public void cancel(String id){cancelled.add(id);}
		void reset(){creates.set(0);cancelled.clear();keys.clear();status=ProviderStatus.PENDING;}
	}
}
