package com.got.retailpos.sales;

import static org.assertj.core.api.Assertions.*; import static org.hamcrest.Matchers.*; import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal; import java.time.Instant; import java.util.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.context.annotation.Import; import org.springframework.http.MediaType; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.test.web.servlet.MockMvc; import org.springframework.transaction.annotation.Transactional;
import com.got.retailpos.TestcontainersConfiguration; import com.got.retailpos.catalog.application.ProductCatalogService; import com.got.retailpos.catalog.domain.Product; import com.got.retailpos.customers.application.CustomerService; import com.got.retailpos.identity.application.*; import com.got.retailpos.identity.domain.*; import com.got.retailpos.identity.security.RetailUserPrincipal; import com.got.retailpos.inventory.application.*; import com.got.retailpos.inventory.infrastructure.*; import com.got.retailpos.sales.application.*; import com.got.retailpos.sales.domain.*;
import jakarta.persistence.EntityManager;

@Import(TestcontainersConfiguration.class) @SpringBootTest @AutoConfigureMockMvc @Transactional
class SalesIntegrationTests {
	@Autowired MockMvc mockMvc; @Autowired ProductCatalogService catalog; @Autowired CustomerService customerService; @Autowired UserAccountService users; @Autowired SupplierService suppliers; @Autowired InventoryService inventory; @Autowired SalesService sales; @Autowired ManagerPinService pins; @Autowired InventoryBalanceRepository balances; @Autowired StockMovementRepository movements; @Autowired JdbcTemplate jdbc; @Autowired EntityManager entityManager;
	Product product; RetailUserPrincipal cashier; RetailUserPrincipal manager;
	@BeforeEach void setup(){var c=catalog.createCategory("sale-"+UUID.randomUUID());product=catalog.createProduct(new ProductCatalogService.ProductInput(c.getId(),"SALE-"+UUID.randomUUID(),null,"สินค้าขาย",new BigDecimal("107.00"),0));cashier=principal("cashier",Role.CASHIER);manager=principal("manager",Role.MANAGER);pins.configure(manager.id(),"correct-password","1234");var supplier=suppliers.create(new SupplierService.SupplierInput("supplier-"+UUID.randomUUID(),null,null));inventory.postReceipt(new InventoryService.ReceiptInput(supplier.getId(),"GR-"+UUID.randomUUID(),Instant.now().minusSeconds(1),null,List.of(new InventoryService.ReceiptItemInput(product.getId(),2,new BigDecimal("60.0000")))),manager.id());}
	@Test void shouldApproveDiscountAndCompleteCashSaleIdempotently() throws Exception {var sale=sales.create(input(1),cashier.id());mockMvc.perform(post("/api/v1/sales/{id}/discount",sale.getId()).with(user(cashier)).with(csrf()).contentType(MediaType.APPLICATION_JSON).content("""
{"type":"AMOUNT","value":7.00,"managerUsername":"%s","managerPin":"1234"}
""".formatted(manager.getUsername()))).andExpect(status().isOk()).andExpect(jsonPath("$.discountApprovedBy",is(manager.id().toString()))).andExpect(jsonPath("$.total",is(100.0))).andExpect(jsonPath("$.vatAmount",is(6.54)));
		mockMvc.perform(post("/api/v1/sales/{id}/checkout/cash",sale.getId()).with(user(cashier)).with(csrf()).header("Idempotency-Key","cash-key-1").contentType(MediaType.APPLICATION_JSON).content("{\"cashReceived\":120.00}" )).andExpect(status().isOk()).andExpect(jsonPath("$.status",is("COMPLETED"))).andExpect(jsonPath("$.changeAmount",is(20.0))).andExpect(jsonPath("$.receiptNumber",startsWith("R-"))).andExpect(jsonPath("$.items[0].unitCostSnapshot",is(60.0)));
		var again=sales.checkoutCash(sale.getId(),"cash-key-1",new BigDecimal("120.00"),cashier.id());assertThat(again.getId()).isEqualTo(sale.getId());assertThat(balances.findById(product.getId()).orElseThrow().getOnHand()).isEqualTo(1);assertThat(movements.findAllByProductId(product.getId(),org.springframework.data.domain.Pageable.unpaged()).stream().filter(m->m.getMovementType()==com.got.retailpos.inventory.domain.MovementType.SALE)).hasSize(1);}
	@Test void shouldRollbackWhenCashIsInsufficient(){var sale=sales.create(input(1),cashier.id());assertThatThrownBy(()->sales.checkoutCash(sale.getId(),"low-cash",new BigDecimal("10.00"),cashier.id())).isInstanceOf(IllegalArgumentException.class);assertThat(balances.findById(product.getId()).orElseThrow().getOnHand()).isEqualTo(2);}
	@Test void shouldRateLimitWrongManagerPin(){for(int i=0;i<4;i++)assertThatThrownBy(()->pins.verify(manager.getUsername(),"9999")).isInstanceOf(InvalidManagerPinException.class);assertThatThrownBy(()->pins.verify(manager.getUsername(),"9999")).isInstanceOf(ManagerPinRateLimitException.class);}
	@Test void shouldForbidInventoryStaffFromSales() throws Exception {var staff=principal("stock",Role.INVENTORY_STAFF);mockMvc.perform(get("/api/v1/sales").with(user(staff))).andExpect(status().isForbidden());}
	@Test void shouldReturnSaleItemsAfterReadTransactionCloses() throws Exception {sales.create(input(1),cashier.id());mockMvc.perform(get("/api/v1/sales").with(user(cashier))).andExpect(status().isOk()).andExpect(jsonPath("$.content[0].items[0].sku",is(product.getSku())));}
	@Test void shouldReturnOnlyCompletedCustomerPurchaseHistory() throws Exception {var customer=customerService.create(new CustomerService.CustomerInput("ลูกค้าประวัติ",null,null,false));sales.create(new SalesService.CreateSaleInput(customer.getId(),List.of(new SalesService.SaleItemInput(product.getId(),1))),cashier.id());var completed=sales.create(new SalesService.CreateSaleInput(customer.getId(),List.of(new SalesService.SaleItemInput(product.getId(),1))),cashier.id());sales.checkoutCash(completed.getId(),"customer-history",new BigDecimal("107.00"),cashier.id());mockMvc.perform(get("/api/v1/customers/{id}/sales",customer.getId()).with(user(cashier))).andExpect(status().isOk()).andExpect(jsonPath("$.totalElements",is(1))).andExpect(jsonPath("$.content[0].status",is("COMPLETED")));}
	@Test void shouldPreventCompletedSaleFromBeingChangedInDatabase(){var sale=sales.create(input(1),cashier.id());sales.checkoutCash(sale.getId(),"immutable-sale",new BigDecimal("107.00"),cashier.id());entityManager.flush();assertThatThrownBy(()->jdbc.update("update sales set total = 1.00 where id = ?",sale.getId())).hasMessageContaining("completed sale history is immutable");}
	private SalesService.CreateSaleInput input(int quantity){return new SalesService.CreateSaleInput(null,List.of(new SalesService.SaleItemInput(product.getId(),quantity)));}
	private RetailUserPrincipal principal(String prefix,Role role){var u=prefix+"-"+UUID.randomUUID();return RetailUserPrincipal.from(users.create(u,"correct-password",u,role));}
}
