package com.got.retailpos.sales.application;

import java.math.*; import java.time.*; import java.util.*;
import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.got.retailpos.catalog.application.ProductCatalogReader; import com.got.retailpos.customers.application.CustomerReader; import com.got.retailpos.identity.application.ManagerPinService; import com.got.retailpos.inventory.domain.StockMovement; import com.got.retailpos.inventory.infrastructure.*; import com.got.retailpos.payments.application.ReceiptNumberGenerator; import com.got.retailpos.payments.domain.Payment; import com.got.retailpos.payments.infrastructure.PaymentRepository; import com.got.retailpos.sales.domain.*; import com.got.retailpos.sales.infrastructure.*; import com.got.retailpos.shared.application.ResourceNotFoundException;

@Service public class SalesService {
	private final ProductCatalogReader products; private final CustomerReader customers; private final StoreSettingsRepository settings; private final SaleRepository sales; private final InventoryBalanceRepository balances; private final StockMovementRepository movements; private final PaymentRepository payments; private final ManagerPinService pins; private final DiscountCalculator discounts; private final ReceiptNumberGenerator receipts;
	public SalesService(ProductCatalogReader products,CustomerReader customers,StoreSettingsRepository settings,SaleRepository sales,InventoryBalanceRepository balances,StockMovementRepository movements,PaymentRepository payments,ManagerPinService pins,DiscountCalculator discounts,ReceiptNumberGenerator receipts){this.products=products;this.customers=customers;this.settings=settings;this.sales=sales;this.balances=balances;this.movements=movements;this.payments=payments;this.pins=pins;this.discounts=discounts;this.receipts=receipts;}
	@Transactional public Sale create(CreateSaleInput input,UUID actor){validateItems(input.items());if(input.customerId()!=null&&!customers.isActiveCustomer(input.customerId()))throw new ResourceNotFoundException("ลูกค้า");var ids=input.items().stream().map(SaleItemInput::productId).toList();var productMap=products.findActiveProducts(ids);if(productMap.size()!=ids.size())throw new ResourceNotFoundException("สินค้าบางรายการ");var config=settings.findById((short)1).orElseThrow();var sale=Sale.draft(input.customerId(),config.isVatEnabled(),config.getVatRate(),actor);for(var item:input.items()){var p=productMap.get(item.productId());sale.addItem(p.id(),p.sku(),p.name(),item.quantity(),p.salePrice());}return sales.save(sale);}
	@Transactional public Sale applyDiscount(UUID id,DiscountInput input){var managerId=pins.verify(input.managerUsername(),input.managerPin());var sale=sales.findByIdForUpdate(id).orElseThrow(()->new ResourceNotFoundException("บิลขาย"));var amount=discounts.calculate(sale.getSubtotal(),input.type(),input.value());sale.applyDiscount(input.type(),input.value().setScale(2,RoundingMode.HALF_UP),amount,managerId);return sale;}
	@Transactional public Sale checkoutCash(UUID id,String key,BigDecimal received,UUID actor){if(key==null||key.isBlank()||key.length()>100)throw new IllegalArgumentException("ต้องระบุ Idempotency-Key ไม่เกิน 100 ตัวอักษร");var existing=sales.findByCheckoutIdempotencyKey(key).orElse(null);if(existing!=null){if(!existing.getId().equals(id))throw new SaleConflictException("Idempotency-Key ถูกใช้กับบิลอื่นแล้ว");return existing;}var sale=sales.findByIdForUpdate(id).orElseThrow(()->new ResourceNotFoundException("บิลขาย"));if(sale.getStatus()==SaleStatus.COMPLETED){if(key.equals(sale.getCheckoutIdempotencyKey()))return sale;throw new SaleConflictException("บิลนี้ชำระเงินแล้ว");}var cash=money(received);if(cash.compareTo(sale.getTotal())<0)throw new IllegalArgumentException("จำนวนเงินสดน้อยกว่ายอดสุทธิ");var sorted=sale.getItems().stream().sorted(Comparator.comparing(i->i.getProductId().toString())).toList();var stockMoves=new ArrayList<StockMovement>();var now=Instant.now();for(var item:sorted){balances.ensureExists(item.getProductId());var balance=balances.findByProductIdForUpdate(item.getProductId()).orElseThrow();var cost=balance.getAverageCost();balance.sell(item.getQuantity());item.snapshotCost(cost);stockMoves.add(StockMovement.sale(item.getProductId(),item.getQuantity(),balance,sale.getId(),actor,now));}sales.flush();movements.saveAll(stockMoves);payments.save(Payment.succeededCash(sale.getId(),sale.getTotal()));sale.complete(receipts.next(),key,cash,actor);return sale;}
	@Transactional(readOnly=true) public Sale findById(UUID id){return sales.findOneById(id).orElseThrow(()->new ResourceNotFoundException("บิลขาย"));}
	@Transactional(readOnly=true) public Page<Sale> findAll(Pageable pageable){var page=sales.findAllBy(pageable);initializeItems(page);return page;}
	@Transactional(readOnly=true) public Page<Sale> findCustomerHistory(UUID customerId,Pageable pageable){if(!customers.isActiveCustomer(customerId))throw new ResourceNotFoundException("ลูกค้า");var page=sales.findAllByCustomerIdAndStatus(customerId,SaleStatus.COMPLETED,pageable);initializeItems(page);return page;}
	private void initializeItems(Page<Sale> page){page.forEach(sale->sale.getItems().size());}
	private void validateItems(List<SaleItemInput> items){if(items==null||items.isEmpty()||items.size()>100)throw new IllegalArgumentException("บิลต้องมีสินค้า 1-100 รายการ");var ids=new HashSet<UUID>();for(var i:items)if(i.productId()==null||i.quantity()<=0||!ids.add(i.productId()))throw new IllegalArgumentException("สินค้าในบิลห้ามซ้ำและจำนวนต้องมากกว่าศูนย์");}
	private BigDecimal money(BigDecimal value){if(value==null||value.signum()<0||value.scale()>2)throw new IllegalArgumentException("จำนวนเงินต้องไม่ติดลบและมีทศนิยมไม่เกิน 2 ตำแหน่ง");return value.setScale(2,RoundingMode.UNNECESSARY);}
	public record CreateSaleInput(UUID customerId,List<SaleItemInput> items){} public record SaleItemInput(UUID productId,int quantity){} public record DiscountInput(DiscountType type,BigDecimal value,String managerUsername,String managerPin){}
}
